# Generated by Django 2.2.7 on 2019-12-30 07:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('title', models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='文档标题')),
                ('desc', models.CharField(help_text='文档描述', max_length=200, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='文档描述')),
                ('image_url', models.URLField(help_text='文档缩略图url', verbose_name='文档缩略图url')),
                ('file_url', models.URLField(help_text='文档url', verbose_name='文档url')),
            ],
            options={
                'verbose_name': '文档',
                'verbose_name_plural': '文档',
                'db_table': 'tb_doc',
            },
        ),
    ]
