# Generated by Django 2.1.3 on 2019-04-16 23:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('title', models.CharField(help_text='课程名', max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='课程名')),
                ('cover_url', models.URLField(help_text='课程封面图URL', verbose_name='课程封面图URL')),
                ('video_url', models.URLField(help_text='课程视频URL', verbose_name='课程视频URL')),
                ('duration', models.FloatField(default=0.0, help_text='课程时长', verbose_name='课程时长')),
                ('desc', models.TextField(help_text='课程简介', verbose_name='课程简介')),
                ('outline', models.TextField(help_text='课程大纲', verbose_name='课程大纲')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'db_table': 'tb_course',
            },
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(help_text='课程分类名', max_length=100, verbose_name='课程分类名')),
            ],
            options={
                'verbose_name': '课程分类',
                'verbose_name_plural': '课程分类',
                'db_table': 'tb_course_category',
            },
        ),
        migrations.CreateModel(
            name='Lectuer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(help_text='姓名', max_length=150, verbose_name='姓名')),
                ('positional_titles', models.CharField(help_text='职称', max_length=150, verbose_name='职称')),
                ('profile', models.TextField(help_text='简介', verbose_name='简介')),
                ('avatar_url', models.ImageField(blank=True, default='avatar/qmpython_avatar.png', help_text='头像', upload_to='lectuer_directory_path', verbose_name='头像')),
            ],
            options={
                'verbose_name': '讲师',
                'verbose_name_plural': '讲师',
                'db_table': 'tb_lectuer',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='course_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseCategory'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Lectuer'),
        ),
    ]
