# Generated by Django 2.1.3 on 2019-03-16 11:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('title', models.CharField(max_length=35, unique=True, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='标题')),
                ('keywords', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='关键词')),
                ('description', models.CharField(blank=True, max_length=120, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='描述')),
                ('content', models.TextField(verbose_name='内容')),
                ('cover_img', models.URLField(verbose_name='封面图')),
                ('is_recommend', models.BooleanField(blank=True, default=False, verbose_name='是否推荐')),
                ('read_num', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
                ('like_num', models.IntegerField(default=0, verbose_name='点赞数')),
            ],
            options={
                'verbose_name_plural': '文章',
                'ordering': ['-create_time'],
                'db_table': 'tb_article',
                'verbose_name': '文章',
            },
        ),
        migrations.CreateModel(
            name='ArticleLikeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='访问IP')),
            ],
            options={
                'db_table': 'tb_article_like_detail',
                'verbose_name': '点赞详情',
            },
        ),
        migrations.CreateModel(
            name='ArticleRecommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(choices=[(1, '第一级'), (2, '第二级'), (3, '第三级'), (4, '第四级'), (5, '第五级'), (6, '第六级')], verbose_name='优先级')),
            ],
            options={
                'verbose_name_plural': '推荐文章',
                'ordering': ['-priority'],
                'db_table': 'tb_article_recommend',
                'verbose_name': '推荐文章',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('image_url', models.URLField(blank=True, default='static/image/qmpython_ad.jpg', verbose_name='图片')),
                ('link_to', models.URLField(verbose_name='网址')),
                ('position', models.CharField(choices=[('top', '上'), ('left', '左'), ('right', '右'), ('bottom', '下')], max_length=10, verbose_name='位置')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('click_num', models.IntegerField(default=0, verbose_name='点击数')),
                ('sort', models.IntegerField(default=0, verbose_name='排序号')),
            ],
            options={
                'verbose_name_plural': '轮播图',
                'ordering': ['sort'],
                'db_table': 'tb_banner',
                'verbose_name': '轮播图',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='分类')),
            ],
            options={
                'verbose_name_plural': '类别',
                'ordering': ['id'],
                'db_table': 'tb_category',
                'verbose_name': '类别',
            },
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='栏目')),
            ],
            options={
                'verbose_name_plural': '栏目',
                'ordering': ['id'],
                'db_table': 'tb_column',
                'verbose_name': '栏目',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=400, verbose_name='评论内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
            ],
            options={
                'verbose_name_plural': '评论',
                'db_table': 'tb_comment',
                'verbose_name': '评论',
            },
        ),
        migrations.CreateModel(
            name='CommentNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='提示时间')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='the_comment', to='article.Comment', verbose_name='所属评论')),
            ],
            options={
                'verbose_name_plural': '评论回复通知',
                'ordering': ['-create_time'],
                'db_table': 'tb_comment_notification',
                'verbose_name': '评论回复通知',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='标签')),
            ],
            options={
                'verbose_name_plural': '标签',
                'db_table': 'tb_tag',
                'verbose_name': '标签',
            },
        ),
    ]
