# Generated by Django 2.1.3 on 2019-03-17 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20190316_1944'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Banner',
            new_name='Advertising',
        ),
        migrations.AlterModelOptions(
            name='advertising',
            options={'ordering': ['sort'], 'verbose_name': '广告', 'verbose_name_plural': '广告'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='is_recommend',
        ),
        migrations.AlterModelTable(
            name='advertising',
            table='tb_advertising',
        ),
    ]
