# Generated by Django 2.1.3 on 2019-03-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20190317_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='link_url',
            field=models.URLField(default='#', verbose_name='链接'),
        ),
    ]
