# Generated by Django 2.1.3 on 2019-03-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_column_link_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover_img',
            field=models.URLField(blank=True, default='/static/image/article/', verbose_name='封面图'),
        ),
        migrations.AlterField(
            model_name='column',
            name='link_url',
            field=models.URLField(verbose_name='链接'),
        ),
    ]
