# Generated by Django 2.1.3 on 2019-03-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20190324_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover_img',
            field=models.URLField(blank=True, default='/static/image/article/article_cover.jpg', verbose_name='封面图'),
        ),
    ]
