# Generated by Django 2.1.3 on 2019-03-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20190326_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover_img',
            field=models.URLField(blank=True, verbose_name='封面图'),
        ),
    ]
