# Generated by Django 2.1.3 on 2019-03-28 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20190326_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertising',
            name='image_url',
            field=models.URLField(verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='position',
            field=models.CharField(choices=[('top_left', '左上'), ('top_right', '右上'), ('right', '右'), ('bottom', '下')], max_length=10, verbose_name='位置'),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='sort',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
    ]
