# Generated by Django 2.1.3 on 2019-04-16 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20190328_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertising',
            name='click_num',
            field=models.IntegerField(default=0, verbose_name='点击量'),
        ),
    ]
