# Generated by Django 2.1.3 on 2019-04-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_auto_20190417_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否显示'),
        ),
    ]
