# Generated by Django 2.1.3 on 2019-04-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.URLField(blank=True, default='http://www.qmpython.com:8000/media/avatar/qmpython_avatar.png', max_length=100, verbose_name='头像'),
        ),
    ]
